const IMAGE = "image/",
  TEXT = "text/",
  APP = "application/",
  AUDIO = "audio/",
  VIDEO = "video/",
  FONT = "font/",
  TEXT_PLAIN = TEXT + "plain",
  TEXT_HTML = TEXT + "html",
  TEXT_CSS = TEXT + "css",
  TEXT_JS = TEXT + "javascript",
  TEXT_YAML = TEXT + "yaml",
  IMAGE_PNG = IMAGE + "png",
  IMAGE_JPEG = IMAGE + "jpeg",
  IMAGE_SVG = IMAGE + "svg+xml",
  IMAGE_GIF = IMAGE + "gif",
  IMAGE_WEBP = IMAGE + "webp",
  IMAGE_AVIF = IMAGE + "avif",
  IMAGE_JXL = IMAGE + "jxl",
  IMAGE_X_ICON = IMAGE + "x-icon",
  APP_JSON = APP + "json",
  APP_XML = APP + "xml",
  APP_PDF = APP + "pdf",
  APP_DOC = APP + "msword",
  APP_DOCX = APP + "vnd.openxmlformats-officedocument.wordprocessingml.document",
  APP_XLS = APP + "vnd.ms-excel",
  APP_XLSX = APP + "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  APP_PPT = APP + "vnd.ms-powerpoint",
  APP_PPTX = APP + "vnd.openxmlformats-officedocument.presentationml.presentation",
  APP_ZIP = APP + "zip",
  APP_7Z = APP + "x-7z-compressed",
  APP_TAR = APP + "x-tar",
  APP_GZ = APP + "gzip",
  APP_WASM = APP + "wasm",
  AUDIO_MPEG = AUDIO + "mpeg",
  VIDEO_MP4 = VIDEO + "mp4",
  FONT_WOFF = FONT + "woff",
  FONT_WOFF2 = FONT + "woff2",
  FONT_TTF = FONT + "ttf",
  FONT_OTF = FONT + "otf";

export const MIME = {
  txt: TEXT_PLAIN,
  html: TEXT_HTML,
  htm: TEXT_HTML,
  css: TEXT_CSS,
  js: TEXT_JS,
  mjs: TEXT_JS,
  yaml: TEXT_YAML,
  yml: TEXT_YAML,
  png: IMAGE_PNG,
  jpg: IMAGE_JPEG,
  jpeg: IMAGE_JPEG,
  svg: IMAGE_SVG,
  gif: IMAGE_GIF,
  webp: IMAGE_WEBP,
  avif: IMAGE_AVIF,
  jxl: IMAGE_JXL,
  ico: IMAGE_X_ICON,
  cur: IMAGE_X_ICON,
  json: APP_JSON,
  xml: APP_XML,
  pdf: APP_PDF,
  doc: APP_DOC,
  docx: APP_DOCX,
  xls: APP_XLS,
  xlsx: APP_XLSX,
  ppt: APP_PPT,
  pptx: APP_PPTX,
  zip: APP_ZIP,
  "7z": APP_7Z,
  tar: APP_TAR,
  gz: APP_GZ,
  wasm: APP_WASM,
  mp3: AUDIO_MPEG,
  mp4: VIDEO_MP4,
  woff: FONT_WOFF,
  woff2: FONT_WOFF2,
  ttf: FONT_TTF,
  otf: FONT_OTF
};

export default (ext) => MIME[ext] || APP + "octet-stream";
