name: Publish cersei_rs

on:
  workflow_dispatch:
  push:
    tags:
      - "cersei_rs@*"

permissions:
  contents: write
  id-token: write

jobs:
  napi-publish:
    uses: ./.github/workflows/napi-publish-template.yml
    secrets: inherit
    with:
      working-directory: "cersei_rs"
