name: 自动同步 ext_mime

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 安装 Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 配置 Git 用户
        run: |
          git config --global user.email action@github.com
          git config --global user.name ${{ github.repository_owner }}

      - name: 运行更新脚本
        run: |
          cd ext_mime
          ./js/gen.js

      - name: 检查改动并执行发布
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain ext_mime/src)" ]; then
            echo "检测到 mime-db 存在更新，开始执行发布流程..."
            cd ext_mime
            ./sh/dist.sh
          else
            echo "未检测到更新，无需发布。"
          fi

      - name: 推送改动
        if: env.NEED_PUSH == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
